### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by dtaylor-530** [lifebeyondfife/Cm93#64]
Thanks for the game. 
Using Visual Studio 2015.

Issues:
**sqlite addin** 
_https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox_
**vdproj addin**  
_https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2015InstallerProjects#qna_
needed?

I downloaded the game as well as its source but neither one allows me to get any further than the screen showing the selected team for a game. All buttons are disabled?

**Comment by lifebeyondfife** [comment]
Hello dtaylor,

Thanks for bearing with my delayed reply.

The vdproj addin is a known issue for later versions of Visual Studio - it's something I need to revisit when I've got a first beta version ready.

With regards to the SQLite addin, what is the problem specifically? I've built the project with Visual Studio 2017 and it worked fine.

The buttons are disabled until you have assigned all players to a starting formation. Drag player rows from the table onto a shirt icon. Once a starting 10 outfield players have been chosen, the buttons will be enabled.

Thanks for your interest!

Iain

**Comment by dtaylor-530** [comment]
Sorry i should have made  my wording clearer/longer:
 i meant it might be worth mentioning those addins are necessary in the readme ( they weren't in at least my version of VS 2015).  That and the thing about the players.
Very similar project using MahApp.Metro, Wuhu [@alexanderkraemer].
I've converted the project to the MahApp.Metro style but can't upload file to github using the desktop because of some random error [128]. It you're interested i can download git and seen if i can do it manually. 
The real interest for me was the simulation algorithm.
