### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by alejandrodt** [lifebeyondfife/Cm93#65]
Hi Iain!

First of all, thanks for this great work and for sharing code! I am very interesting about how it works and how you faced the simulation process!
The first step was to adapt the code to VS2019 and run the game. It works up to match screen, where i have an error. I think there are some files that are not included in the package.

In the file PossessionGraph.cs, there are four lines asking for files i dont have:
Data = new StreamWriter(File.Create(@"C:\Users\iain\Desktop\data.csv"));
Passes = new StreamWriter(File.Create(@"C:\Users\iain\Desktop\passes.csv"));
Shots = new StreamWriter(File.Create(@"C:\Users\iain\Desktop\shots.csv"));
Chain = new StreamWriter(File.Create(@"C:\Users\iain\Desktop\chain.csv"));

The game crashes in match screen because it doesnt find the files above.

do you have them? could you please share it?
Thanks a lot Iain!!!!

**Comment by lifebeyondfife** [comment]
Thank you so much for the interest in Cm93. I learned a lot from getting it
as far as I did - taking the decision to stop working on it was a tough
one, but ultimately one which saved my sanity. Side projects need to be
appropriately scoped and the way I'd made this one was just too big to
complete.

To get back to your question, I hope I have good news. From my memory, the
purpose of those files is purely for debugging what's going on in the AI
model i.e. they are output files which show the state of the game
simulation. If you change the code to be locations you can access, playing
the game should create these.

I'll look at the code now to double-check my thinking, but please get back
in touch if that doesn't fix the issue.

**Comment by alejandrodt** [comment]
Aah! Thanks Iain! I didnt read properly the full code of the file (all night working and after, checking this osom project). I will change the address of the files creation in order to have it into my system.

Thanks again Iain!
